return {
	"nvim-treesitter/nvim-treesitter",
	branch = "master",
	lazy = false,
	build = ":TSUpdate",
	opts = {},
	config = function()
		require("nvim-treesitter.configs").setup({
			ensure_installed = {
				"asm",
				"nasm",
				"c",
				"cpp",
				"cmake",
				"make",
				"bash",
				"html",
				"css",
				"javascript",
				"typescript",
				"dockerfile",
				"json",
				"toml",
				"lua",
				"markdown",
				"markdown_inline",
				"python",
				"rust",
				"sql",
			},
			auto_install = false,
			highlight = { enable = true },
		})
	end,
}
