return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter.configs").setup({
			highlight = { enable = true },
			indent = { enable = true },
			ensure_installed = {
				"asm",
				"bash",
				"c",
				"cmake",
				"cpp",
				"css",
				"dockerfile",
				"gitignore",
				"html",
				"javascript",
				"json",
				"lua",
				"make",
				"nasm",
				"php",
				"python",
				"regex",
				"rust",
				"typescript",
				"scss",
				"yaml",
			},
			sync_installed = true,
			auto_install = true,
		})
	end,
}
